### ISSUE TITLE
Crash when previewed in KDE's System Settings Color KCM

### ISSUE THREAD

**Issue by IlyaBizyaev** [FedoraQt/adwaita-qt#124]
```
[KCrash Handler]
#6  QWidgetPrivate::windowHandle (this=<optimized out>) at ../../include/QtWidgets/5.13.1/QtWidgets/private/../../../../../src/widgets/kernel/qwidget_p.h:1021
#7  QWidget::windowHandle (this=this@entry=0x0) at kernel/qwidget.cpp:2664
#8  0x00007ff5ea41c857 in Adwaita::Style::drawComboBoxLabelControl (this=0x5612f616e8f0, option=0x5612f6705f10, painter=0x7fff29ba2520, widget=0x0) at /usr/src/debug/adwaita-qt-1.0-lp151.2.3.x86_64/style/adwaitastyle.cpp:4630
#9  0x00007ff5ea419a6f in Adwaita::Style::drawControl (this=0x5612f616e8f0, element=QStyle::CE_ComboBoxLabel, option=0x5612f6705f10, painter=0x7fff29ba2520, widget=0x0) at /usr/src/debug/adwaita-qt-1.0-lp151.2.3.x86_64/style/adwaitastyle.cpp:1130
#10 0x00007ff60027030a in KQuickStyleItem::paint (this=this@entry=0x5612f821e650, painter=painter@entry=0x7fff29ba2520) at /usr/src/debug/qqc2-desktop-style-5.63.0-lp151.67.1.x86_64/plugin/kquickstyleitem.cpp:1579
#11 0x00007ff6002706cc in KQuickStyleItem::updatePolish (this=0x5612f821e650) at /usr/src/debug/qqc2-desktop-style-5.63.0-lp151.67.1.x86_64/plugin/kquickstyleitem.cpp:1793
#12 0x00007ff62bb2dccf in QQuickWindowPrivate::polishItems (this=0x5612f71556a0) at /usr/src/debug/libqt5-qtdeclarative-5.13.1-lp151.2.1.x86_64/src/quick/items/qquickwindow.cpp:311
#13 0x00007ff62bbf11c4 in QQuickRenderControl::polishItems (this=<optimized out>) at /usr/src/debug/libqt5-qtdeclarative-5.13.1-lp151.2.1.x86_64/src/quick/items/qquickrendercontrol.cpp:267
#14 0x00007ff62c1dec65 in QQuickWidgetPrivate::render (this=this@entry=0x5612f86ee2b0, needsSync=<optimized out>) at /usr/src/debug/libqt5-qtdeclarative-5.13.1-lp151.2.1.x86_64/src/quickwidgets/qquickwidget.cpp:296
```
See [a related report on KDE's Bugzilla](https://bugs.kde.org/show_bug.cgi?id=413617) for explanation.

**Comment by grulja** [comment]
Fixed with https://github.com/FedoraQt/adwaita-qt/commit/1d09ba4c764a62e4275ad0667ec3e61916fa9957.
